name: .NET

on:
  push:
    branches: [ forked-dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Deploy app
      run: dotnet pack -c Release -o publish Monzo/Monzo.csproj
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: publish
    - name: Publish Nuget Package
      if: github.actor != 'dependabot[bot]'
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/brettjenkins/index.json -n GitHub -u ${{ github.actor }} -p ${{ secrets.GH_PAT }} --store-password-in-clear-text
        dotnet nuget push "packages/*"  --source "GitHub"  

